base/urls.py
from django.urls import path
from . import views
from .views import trades_by_timeframe


#from django.contrib.auth import views as auth_views

urlpatterns = [
	path('', views.home, name="home"),
	path('signin/', views.signin, name="signin"),
	path('signout/', views.signout, name="signout"),
	path('signup/', views.signup, name="signup"),
	path('profile/<str:username>/', views.profile, name="profile"),
	#password_reset
	#password_reset_done
	#password_reset_confirm
	#password_reset_complete
    path('trades/', trades_by_timeframe, name='trades'),
	path('trades/<str:timeframe>/', trades_by_timeframe, name='trades_by_timeframe'),
    path('trade/<int:trade_id>/', views.trade, name='trade'),
	
	path('order/<str:pk>/', views.order, name="order"),
	path('tag/<str:pk>/', views.tag, name="tag"),
	
	path('brokerage/<str:pk>/', views.brokerage, name="brokerage"),
	path('add-brokerage/', views.addBrokerage, name="add-brokerage"),
	path('update-brokerage/<str:pk>/', views.updateBrokerage, name="update-brokerage"),
	path('delete-brokerage/<str:pk>/', views.deleteBrokerage, name="delete-brokerage"),

	
	
]

django_project/urls.py
from django.contrib import admin
from django.urls import path, include





urlpatterns = [
    path('admin/', admin.site.urls),
	path('', include('base.urls')),
	]

base/models.py
from django.contrib.auth.models import User
from base.utils import time_difference_simplifier
from django.db import models

class Brokerage(models.Model):
	
    NAME_CHOICES = (
        ('interactive_brokers', 'Interactive Brokers'),
        ('tradezero', 'TradeZero'),
        ('binance', 'Binance'),
        ('coinbase', 'Coinbase'),
        ('kucoin', 'KuCoin'),
        ('bybit', 'Bybit'),
        ('okx', 'OKX'),
        ('bitstamp', 'Bitstamp'),
        ('bitfinex', 'Bitfinex'),
        ('gate_io', 'Gate.io'),
        ('gemini', 'Gemini'),
        ('bitget', 'Bitget'),
        ('huobi', 'Huobi'),
        ('mercado_bitcoin', 'Mercado Bitcoin'),
        ('foxbit', 'Foxbit')
        # ... add more names as needed
		# Brokerages are hardcoded as they change infrequently. 
        # If any changes are needed, they will likely be minor (addition or removal of one or two brokerages).
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=20, choices=NAME_CHOICES)
    alias = models.CharField(max_length=20, null=True)
    login = models.CharField(max_length=100)
    key = models.CharField(max_length=100)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f"Brokerage: {self.name} - {self.alias}"

class Trade(models.Model):
    symbol = models.CharField(max_length=10)
    long_short = models.CharField(max_length=5)
    win_loss = models.CharField(max_length=5)
    quantity_of_orders = models.IntegerField()
    quantity_trade_asset = models.FloatField()
    trade_money = models.FloatField()
    trade_result = models.FloatField()
    trade_result_percentage = models.FloatField()
    trade_brokerage_commission = models.FloatField()
    date_open = models.DateTimeField()
    date_close = models.DateTimeField()
    holding_time = models.CharField(max_length=20)
	
    class Meta:
        ordering = ['-date_close']
    def __str__(self):
        return f"Trade: {self.symbol}- {self.win_loss}: {self.trade_result} - {self.holding_time}"

class Order(models.Model):
    BUY_SELL_CHOICES = (
        ('buy', 'buy'),
        ('sell', 'sell')
	)
    OPEN_CLOSE_CHOICES = (
        ('open', 'open'),
        ('close', 'close'),
		('flip', 'flip')
	)
    trade = models.ForeignKey(Trade, null=True, blank=True, on_delete=models.SET_NULL, related_name="orders")
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    brokerage = models.ForeignKey(Brokerage, on_delete=models.CASCADE)  # turn SET NULL after testing
    client_brokerage_account_id = models.CharField(max_length=20, null=True)
    listing_exchange = models.CharField(max_length=20)
    asset_class = models.CharField(max_length=20)
    symbol = models.CharField(max_length=10)
    brokerage_order_id = models.CharField(max_length=20)
    date_time = models.DateTimeField()
    time_zone = models.CharField(max_length=5)
    buy_sell = models.CharField(max_length=5, choices=BUY_SELL_CHOICES)
    open_close = models.CharField(max_length=5, choices=OPEN_CLOSE_CHOICES)  # binance dont have this :S 
    quantity = models.FloatField()
    currency = models.CharField(max_length=10, null=True)
    order_price = models.FloatField()
    order_money = models.FloatField()
    brokerage_commission = models.FloatField(null=True, default=0.0)
    net_money = models.FloatField()
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    processed = models.BooleanField(default=False)  # true is already inside a trade

    class Meta:
        ordering = ['-date_time']

    @classmethod
    def generate_trades_from_unprocessed_orders(cls):
        unprocessed_orders = cls.objects.filter(processed=False)
        
        quantity_sum = {}
        orders_within_trade = {}

        for order in unprocessed_orders:
            symbol = order.symbol
            quantity = order.quantity

            if symbol not in quantity_sum:
                quantity_sum[symbol] = 0
                orders_within_trade[symbol] = []

            quantity_sum[symbol] += quantity
            orders_within_trade[symbol].append(order)

            if quantity_sum[symbol] == 0:
                long_short = "long" if orders_within_trade[symbol][0].open_close == "O" and orders_within_trade[symbol][0].buy_sell == "buy" else "short"
                trade_result = sum(o.net_money for o in orders_within_trade[symbol])
                trade_money = sum(abs(o.order_money) for o in orders_within_trade[symbol] if o.open_close == "open")
                quantity_trade_asset = sum(abs(o.quantity) for o in orders_within_trade[symbol] if o.open_close == "open")
                trade_result_percentage = trade_result / trade_money
                win_loss = "win" if trade_result > 0 else "loss"
                trade_brokerage_commission = sum(o.brokerage_commission for o in orders_within_trade[symbol] if o.brokerage_commission)
                date_open = min(o.date_time for o in orders_within_trade[symbol])
                date_close = max(o.date_time for o in orders_within_trade[symbol])

                trade = Trade(
                    symbol=symbol,
                    long_short=long_short,
                    win_loss=win_loss,
					trade_result=trade_result,
					trade_money=trade_money,
                    quantity_of_orders=len(orders_within_trade[symbol]),
                    quantity_trade_asset=quantity_trade_asset,
                    trade_result_percentage=trade_result_percentage,
                    trade_brokerage_commission=trade_brokerage_commission,
                    date_open=date_open,
                    date_close=date_close,
                    holding_time=time_difference_simplifier(date_open, date_close),
                )
                trade.save()

                for o in orders_within_trade[symbol]:
                    o.trade = trade
                    o.save()

                # Reset for next group
                orders_within_trade[symbol] = []

        # After generating trades, mark orders as processed
        unprocessed_orders.update(processed=True)
    
    def __str__(self):
        return f"Order: {self.symbol} {self.date_time} - {self.id}"


class Tag(models.Model):
    name = models.CharField(max_length=50)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    
"""
class Quotes(models.Model):
    asset_class = models.CharField(max_length=20)
    symbol = models.CharField(max_length=10)
    date = models.DateTimeField()
    currency_primary = models.CharField(max_length=5)
    high_price = models.FloatField()
    low_price = models.FloatField()
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
"""

trades/models.py
from django.db import models

# Create your models here.




"""

from django.contrib.auth.models import User

class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    client_brokerage_account_id = models.CharField(max_length=20)
    brokerage = models.CharField(max_length=20)
    listing_exchange = models.CharField(max_length=20)
    asset_class = models.CharField(max_length=20)
    symbol = models.CharField(max_length=10)
    brokerage_order_id = models.CharField(max_length=20)
    date_time = models.DateTimeField()
    time_zone = models.CharField(max_length=5)
    buy_sell = models.CharField(max_length=5)
    open_close = models.CharField(max_length=1)
    quantity = models.FloatField()
    currency_primary = models.CharField(max_length=5)
    order_price = models.FloatField()
    order_money = models.FloatField()
    brokerage_commission = models.FloatField()
    net_money = models.FloatField()

    def __str__(self):
        return f"Order {self.id}"

    @classmethod
    def create_trade(cls):
        orders = cls.objects.all()
        trades = []
        quantity_sum = {}
        orders_within_trade = {}

        for order in orders:
            symbol = order.symbol
            quantity = order.quantity

            if symbol not in quantity_sum:
                quantity_sum[symbol] = 0
                orders_within_trade[symbol] = []

            quantity_sum[symbol] += quantity
            orders_within_trade[symbol].append(order)

            if quantity_sum[symbol] == 0:
                long_short = "LONG" if orders_within_trade[symbol][0].open_close == "O" and orders_within_trade[symbol][0].buy_sell == "BUY" else "SHORT"
                trade_result = sum(order.net_money for order in orders_within_trade[symbol])
                trade_amount = sum(abs(order.order_money) for order in orders_within_trade[symbol] if order.open_close == "O")
                trade_shares_quantity = sum(abs(order.quantity) for order in orders_within_trade[symbol] if order.open_close == "O")
                trade_result_percentage = trade_result / trade_amount
                win_loss = "WIN" if trade_result > 0 else "LOSS"
                trade_fee = sum(order.brokerage_commission for order in orders_within_trade[symbol])
                trade_asset = orders_within_trade[symbol][0].asset_class
                trade_enter_date = min(order.date_time for order in orders_within_trade[symbol])
                trade_exit_date = max(order.date_time for order in orders_within_trade[symbol])

                trades.append({
                    "Symbol": symbol,
                    "Asset class": trade_asset,
                    "Long/Short": long_short,
                    "Win/Loss": win_loss,
                    "Number of Orders": len(orders_within_trade[symbol]),
                    "Quantity": quantity_sum[symbol],
                    "Trade Shares/Contracts Quantity": trade_shares_quantity,
                    "Trade Result": trade_result,
                    "Trade Amount": trade_amount,
                    "Trade Result Percentage": trade_result_percentage,
                    "Trade Fee": trade_fee,
                    "Enter Date": trade_enter_date,
                    "Exit Date": trade_exit_date,
                    #"Holding time": time_difference_simplifier(trade_enter_date, trade_exit_date),
                    "Orders": orders_within_trade[symbol],
                })
                # Reset for the next group
                orders_within_trade[symbol] = []

        return trades
"""

base/forms.py
from django.forms import ModelForm
from .models import Brokerage

class BrokerageForm(ModelForm):
	class Meta:
		model = Brokerage
		fields = '__all__'
		exclude = ['user']

trades/views.py
from django.shortcuts import render

# Create your views here.

base/templates/base/brokerage.html
{% extends 'main.html' %}
{% block content %}
<h1>Trinfo - Brokerage {{ brokerage.get_name_display }}</h1>
        <p>{{{ brokerage.get_name_display }}</p>
		<p>{{brokerage.key}}</p>
		<p>{{brokerage.created}}</p>
		<p>{{brokerage.updated}}</p>

{% endblock content %}

base/templates/base/brokerage_form.html
{% extends 'main.html' %}
{% block content %}
<h1>Trinfo - Add Brokerage to your account</h1>

    <form method="POST" action="">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Add</button>
    </form>

{% endblock content %}

base/templates/base/delete.html
{% extends 'main.html' %}
{% block content %}
<h1>Delete {{{ brokerage.get_name_display }}</h1>
	<h3>Are you sure you want to delete the connection to {{{ brokerage.get_name_display }}/</h3>
		<p>All trades from this connection will be deleted. That is no return...</p>
    <form method="POST" action="">
		{% csrf_token %}
        {{ form.as_p }}
		<a href="{{ request.META.HTTP_REFERER }}">Go back</a>
        <button type="submit">Delete</button>
    </form>
{% endblock content %}

base/templates/base/home.html
{% extends 'main.html' %}
{% block content %}
<h1>Trinfo Home</h1>
<div>
	<h2>Last Orders</h2>
	<div>
		{% for order in order %}
			<div>
				<a href="{% url 'profile' order.user.username%}"><span>@{{order.user.username}}</span></a>
				<a href="/order/{{order.id}}"><h5>{{order.symbol}}: {{order.buy_sell}}</h5></a>
				<small>{{order.created}}</small>
				<hr>
				
			</div>
		{% endfor %}
	</div>

{% endblock content %}

base/templates/base/order.html
{% extends 'main.html' %}
{% block content %}
<h1>Trinfo - Order {{order.symbol}}</h1>
        <p>{{order.buy_sell}}</p>
		<p>{{order.open_close}}</p>
		<p>{{order.asset_class}}</p>
		<p>{{order.order_price}}</p>

{% endblock content %}

base/templates/base/profile.html
{% extends 'main.html' %}
{% block content %}
<h1>Trinfo - @{{user.username}} </h1>


{% if user.is_authenticated and user == request.user %}
	<h2>Brokerages <button><a href="{% url 'add-brokerage' %}">Add connection</a></button></h2>

<table>
	<thead>
		<tr>
			<th>Alias</th>
			<th>Brokerage</th>
			<th>Created</th>
			<th>Last updated</th>
			<th></th>
			<th></th>
		</tr>
	</thead>
  <tbody>
    {% for brokerage in brokerage %}
    <tr>
    	<td><a href="{% url 'update-brokerage' brokerage.id %}">{{brokerage.alias}}</a></td>
    	<td>{{ brokerage.get_name_display }}</td>
    	<td><small>{{ brokerage.created }}</small></td>
		<td><small>{{ brokerage.updated }}</small></td>
		<td>
			<form method="post">
	    		{% csrf_token %}
				<input type="hidden" name="brokerage_id" value="{{ brokerage.id }}">
	    		<button type="submit" name="run_brokerage_connection">Fetch trades</button>
			</form>
		</td>
		<td><button><a href="{% url 'delete-brokerage' brokerage.id %}">Delete</a></button></td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endif %}

	<h2>Last Orders</h2>
	<table border="1">
    <thead>
        <tr>
			<th>Brokerage</th>
			<th>Asset Class</th>
            <th>Symbol</th>
            <th>Buy/Sell</th>
            <th>Date Time</th>
            <th>Open/Close</th>
            <th>Quantity</th>
            <th>Order Price</th>
            <th>Order Money</th>
            <th>Brokerage Commission</th>
            <th>Net Money</th>
        </tr>
    </thead>
    <tbody>
        {% for order in order %} <!-- Fixed the loop variable -->
            <tr>                
				<td>{{ order.brokerage.get_name_display }}</td>
				<td>{{ order.asset_class|capfirst }}</td>
                <td><a href="/order/{{ order.id }}">{{ order.symbol }}</a></td>
                <td>{{ order.buy_sell|capfirst }}</td>
                <td>{{ order.date_time }}</td>
                <td>{{ order.open_close|capfirst  }}</td>
                <td>{{ order.quantity }}</td>
                <td>{{ order.order_price }}</td>
                <td>{{ order.currency }} {{ order.order_money|floatformat:2 }}</td>
                <td>{{ order.currency }} {{ order.brokerage_commission|floatformat:2 }}</td>
                <td>{{ order.currency }} {{ order.net_money|floatformat:2 }}</td>
            </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock content %}

base/templates/base/signin.html
{% extends 'main.html' %}
{% block content %}
  <h1>Login</h1>
  
  <form method="POST" action="">
    {% csrf_token %}
    <label for="username">Username:</label>
    <input type="text" id="username" name="username" placeholder="Enter your username" required>
    <br>
    <label for="password">Password:</label>
    <input type="password" id="password" name="password" placeholder="Enter your password"required>
    <br>
    <button type="submit">Login</button>
  </form>
	<p>Don't you have an account? <a href="{% url 'signup' %}" >Create account</a></p>
  
{% endblock content %}

base/templates/base/signup.html
{% extends 'main.html' %}
{% block content %}
  <h1>Create account</h1>

    <form method="POST" action="">
		{% csrf_token %}
		{{form.as_p}}
		<button type="submit">Create account</button>
    </form>
	<p>Already have an account? <a href="{% url 'signin' %}" >Login</a></p>
  
{% endblock content %}

base/templates/base/tag.html
{% extends 'main.html' %}
{% block content %}
<h1>Trinfo Tag</h1>
        <p>This is my first web page.</p>
        <div>It contains a 
			{% for tag in tags %}
				<div>
					<a href="/tag/{{tag.name}}"><h5>{{tag.name}}</h5></a>
				</div>
			{% endfor %}
        </div>

{% endblock content %}

base/templates/base/trade.html
{% extends 'main.html' %}

{% block content %}
<h1>Trade Details for {{ trade.symbol }}</h1>
 {{ plot_div|safe }}
<table border="1">
    <thead>
        <tr>
            <th>Symbol</th>
            <th>Long/Short</th>
            <th>Win/Loss</th>
            <th>Quantity of Orders</th>
            <th>Quantity Trade Asset</th>
            <th>Trade Money</th>
            <th>Trade Result</th>
            <th>Trade Result Percentage</th>
            <th>Trade Brokerage Commission</th>
            <th>Date Open</th>
            <th>Date Close</th>
            <th>Holding Time</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>{{ trade.symbol }}</td>
            <td>{{ trade.long_short }}</td>
            <td>{{ trade.win_loss }}</td>
            <td>{{ trade.quantity_of_orders }}</td>
            <td>{{ trade.quantity_trade_asset }}</td>
            <td>{{ trade.trade_money|floatformat:2 }}</td>
            <td>{{ trade.trade_result|floatformat:2 }}</td>
            <td>{{ trade.trade_result_percentage|floatformat:2 }}</td>
            <td>{{ trade.trade_brokerage_commission|floatformat:2 }}</td>
            <td>{{ trade.date_open }}</td>
            <td>{{ trade.date_close }}</td>
            <td>{{ trade.holding_time }}</td>
        </tr>

    </tbody>
</table>

<h2>Orders Associated with this Trade</h2>
<table border="1">
    <thead>
        <tr>
            <th>Listing Exchange</th>
            <th>Asset Class</th>
            <th>Symbol</th>
            <th>Date Time</th>
            <th>Time Zone</th>
            <th>Buy/Sell</th>
            <th>Open/Close</th>
            <th>Quantity</th>
            <th>Currency</th>
            <th>Order Price</th>
            <th>Order Money</th>
            <th>Brokerage Commission</th>
            <th>Net Money</th>
            <th>Processed</th>
        </tr>
    </thead>
    <tbody>
        {% for order in trade.orders.all %}
        <tr>
            <td>{{ order.listing_exchange }}</td>
            <td>{{ order.asset_class }}</td>
            <td>{{ order.symbol }}</td>
            <td>{{ order.date_time }}</td>
            <td>{{ order.time_zone }}</td>
            <td>{{ order.buy_sell }}</td>
            <td>{{ order.open_close }}</td>
            <td>{{ order.quantity }}</td>
            <td>{{ order.currency }}</td>
            <td>{{ order.order_price }}</td>
            <td>{{ order.order_money|floatformat:2  }}</td>
            <td>{{ order.brokerage_commission|floatformat:2  }}</td>
            <td>{{ order.net_money|floatformat:2 }}</td>
            <td>{{ order.processed }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>



{% endblock %}

base/templates/base/trade_journal.html
{% extends 'main.html' %}
{% block content %}
<h1>Trade journal </h1>
{% endblock content %}

base/templates/base/trades.html
{% extends 'main.html' %}

{% block content %}
{% if timeframe == "day" %}
    <h1>Trades by Day</h1>
{% elif timeframe == "week" %}
    <h1>Trades by Week</h1>
{% elif timeframe == "month" %}
    <h1>Trades by Month</h1>
{% else %}
    <h1>All Trades</h1>
{% endif %}
<button><a href="{% url 'trades_by_timeframe' timeframe='day'%}">Trades by day</a></button>
<button><a href="{% url 'trades_by_timeframe' timeframe='week'%}" >Trades by week</a></button>
<button><a href="{% url 'trades_by_timeframe' timeframe='month'%}">Trades by month</a></button>
<button><a href="{% url 'trades_by_timeframe' timeframe='all'%}">All Trades</a></button>

{% for group in grouped_trades_with_stats %}
{% if timeframe == "day" %}
    <h2>{{ group.date|date:"Y-m-d" }}</h2>
{% elif timeframe == "week" %}
    <h2>Week of {{ group.date|date:"Y-W" }}</h2>
{% elif timeframe == "month" %}
    <h2>{{ group.date|date:"Y F" }}</h2>
{% elif timeframe == "all" %}

{% else %}
    <h2>{{ group.date|date:"Y-m-d" }}</h2>
{% endif %}

<!-- Displaying the sums -->
<!-- Displaying the sums -->
<p><strong>Total Trade Result:</strong> {{ group.stats.total_trade_result|floatformat:2 }}</p>
<p><strong>Total Trade Result Percentage:</strong> {{ group.stats.total_trade_result_percentage|floatformat:2 }}%</p>
<p><strong>Average Trade Money:</strong> {{ group.stats.average_trade_money|floatformat:2 }}</p>
<p><strong>Win rate:</strong> {{ group.stats.win_rate|floatformat:2 }}%</p>
<p><strong>Total Trade Money:</strong> {{ group.stats.total_trade_money|floatformat:2 }}</p>

<p><strong>Total Money Won:</strong> {{ group.stats.total_money_win|floatformat:2 }}</p>
<p><strong>Percentage of Money Won:</strong> {{ group.stats.total_money_win_percentage|floatformat:2 }}%</p>
<p><strong>Total Money in Winning Trades:</strong> {{ group.stats.total_trade_money_when_win|floatformat:2 }}</p>
<p><strong>Total Trades Won:</strong> {{ group.stats.total_trades_win }}</p>

<p><strong>Total Money Lost:</strong> {{ group.stats.total_money_loss|floatformat:2 }}</p>
<p><strong>Percentage of Money Lost:</strong> {{ group.stats.total_money_loss_percentage|floatformat:2 }}%</p>
<p><strong>Total Money in Losing Trades:</strong> {{ group.stats.total_trade_money_when_loss|floatformat:2 }}</p>
<p><strong>Total Trades Lost:</strong> {{ group.stats.total_trades_loss }}</p>

<p><strong>Total Quantity of Trades:</strong> {{ group.stats.total_of_trades }}</p>
<p><strong>Total Quantity of Orders:</strong> {{ group.stats.total_of_orders }}</p>
<p><strong>Total Brokerage Commission:</strong> {{ group.stats.total_trade_brokerage_commission|floatformat:2 }}</p>



<table>
        <thead>
            <tr>
                <th>Symbol</th>
                <th>Long/Short</th>
                <th>Win/Loss</th>
                <th>Quantity of Orders</th>
                <th>Quantity Trade Asset</th>
                <th>Trade Money</th>
                <th>Trade Result</th>
                <th>Trade Result Percentage</th>
                <th>Trade Brokerage Commission</th>
                <th>Date Open</th>
                <th>Date Close</th>
                <th>Holding Time</th>
                <th>Details</th>
            </tr>
        </thead>
        <tbody>
            {% for trade in group.trades %}
            <tr>
                <td>{{ trade.symbol }}</td>
                <td>{{ trade.long_short }}</td>
                <td>{{ trade.win_loss }}</td>
                <td>{{ trade.quantity_of_orders }}</td>
                <td>{{ trade.quantity_trade_asset }}</td>
                <td>{{ trade.trade_money|floatformat:2 }}</td>
                <td>{{ trade.trade_result|floatformat:2 }}</td>
                <td>{{ trade.trade_result_percentage|floatformat:2 }}</td>
                <td>{{ trade.trade_brokerage_commission|floatformat:2 }}</td>
                <td>{{ trade.date_open }}</td>
                <td>{{ trade.date_close }}</td>
                <td>{{ trade.holding_time }}</td>
                <td><a href="{% url 'trade' trade.id %}">View Orders</a></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
{% endfor %}
{% endblock %}